### ISSUE TITLE
Help Troubleshooting Teams Creation. Graph API returns some kind of Error

### ISSUE THREAD

**Issue by amorrowbellarmine** [microsoft/o365-moodle#1227]
I'm hoping someone can help me troubleshoot a problem. In our Moodle environment we have Team sync set to custom and only enable it for courses that faculty explicitly request if for. Once we enable the Teams check box for a course, we wait for the groupcreate cron job to run (running every minute). Sometimes the team is created with no issues. Other times the teams are not created. When a team fails to be created the objectid written into the local_o365_objects table is only '{' which leads me to believe the Graph API returned an error and the '{' is the start of the JSON body. I want to know what data is being sent to the Graph API, but there isn't any tracing in the "create_class_team" function from unified.php. Is there an easy way to figure out what the body was that the function sent to the Graph API? I feel like adding mtrace to the function would help be a start.

In the mean time I wrote a PowerShell script that practically mimics the groupcreate functionality and fixes the problem of a team not existing and the db entry having the incorrect objectid.

Environment Details:
OS: Ubuntu 18.04
Moodle: v3.6.6
Plugin: 3.6.0.3 (2018120303)

I disabled the cron job for groupcreate and then executed it manually using the --showsql and --showdebugging commands. Unfortunately there isn't any information of what was sent to the Graph API. Here is a snippet.
```
$sudo -u www-data /usr/bin/php /var/www/html/moodle/admin/tool/task/cli/schedule_task.php --execute='\local_o365\task\groupcreate' --showsql --showdebugging

--------------------------------
Created class team { for course #23432
--------------------------------
INSERT INTO mdl_local_o365_objects (type,subtype,objectid,moodleid,o365name,timecreated,timemodified) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id
[array (
  'type' => 'group',
  'subtype' => 'course',
  'objectid' => '{',
  'moodleid' => '23432',
  'o365name' => '2020SP Sectional Anatomy (RTT-322-01)',
  'timecreated' => 1585232524,
  'timemodified' => 1585232524,
)]
--------------------------------
Query took: 0.015636920928955 seconds.
--------------------------------
Recorded group object ({) into object table with record id 33886
--------------------------------
INSERT INTO mdl_local_o365_objects (type,subtype,objectid,moodleid,o365name,timecreated,timemodified) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id
[array (
  'type' => 'group',
  'subtype' => 'courseteam',
  'objectid' => '{',
  'moodleid' => '23432',
  'o365name' => '2020SP Sectional Anatomy (RTT-322-01)',
  'timecreated' => 1585232524,
  'timemodified' => 1585232524,
)]
--------------------------------
```

**Comment by nenorojas** [comment]
Hi 

We noticed this issue when trying to sync a course and the issue was because:

1) Microsoft API does not allow more than 1 owner (more than 1 teacher enrolled to a Moodle course) to be set at course team creation.
2) Microsoft team restricts course team description to 1024 characters (Moodle course description).

Please check if your course fits in one of the items above, if yes, a new version will be released soon to sort that.

Regards

**Comment by nenorojas** [comment]
Issue related #1222

**Comment by amorrowbellarmine** [comment]
Yes. I have courses that fit both issues. I discovered the description character limit and submitted a pull request patch to fix it. See #1221 . I was aware of the owner issue independently from building teams using the Graph API myself, but didn't realize the plugin didn't take that problem into account.

**Comment by avegys** [comment]
Hi amorrowbellarmine,

Thank you for reporting the issue. We have just released new version of local_o365 plugin for Moodle 3.7 and Moodle 3.8 which solves these teams creation issues.

Best regards,
Andrius

**Comment by montypanday** [comment]
Hi,

I have recently stumbled on this one and it is sad that this issue wasn't resolved for the last Long term support version 3.5

Some organizations stick to LTS versions and only update when the next LTS version is available.

It would be good if you guys can support atleast the current LTS version. Happy to help out.

Otherwise, we would have to ditch Moodle - Teams integration this year which does not help our students in the current circumstances. 

Kind Regards
Monty Panday
