### ISSUE TITLE
Sync users from Microsoft Entra ID skiptoken and deltatoken API call error

### ISSUE THREAD

**Issue by RayCoSector** [microsoft/o365-moodle#2535]
Hi all, 

Has anyone come across this before (see below), I'm thinking that it might be caused due to multiple accounts using the same email address in the Active Directory.

What happens is that the next sync then is a forced to do a full sync, after the full sync completes in 5 or so hours the next sync is then like the below, completing in around 1 second and the next sync is a full sync and around it goes. All seems to work okay.. it is just a little unnerving as to why it is happening ?? 

Moodle 4.1.9
O365 plugins 4.1.5

```
Execute scheduled task: Sync users from Microsoft Entra ID (local_o365\task\usersync)
... started 10:01:01. Current memory use 21.5 MB.
...... Starting sync
...... Using deltatoken.
...... Using delta sync.
...... Contacting Microsoft Entra ID...
...... Error in delta usersync: Error in API call: Invalid request: Both skiptoken and deltatoken can't be in the same request.
...... Resetting delta tokens.
...... Got response from Microsoft Entra ID
...... Clearing deltatoken (none received)
...... No users received to sync.
...... Suspend/delete users feature skipped because it was run less than 1 day ago.
...... Sync process finished.
... used 3 dbqueries
... used 0.84352517127991 seconds
Scheduled task complete: Sync users from Microsoft Entra ID (local_o365\task\usersync)
```

Regards,
Ray.

**Comment by RayCoSector** [comment]
I removed all the duplicate users and the issue is still in place. 

Not sure if Debug will show more information..

**Comment by RayCoSector** [comment]
Just to add, I've now seen the same on another site - using 4.1.5 plugins on Moodle 4.1.9

Each alternate run it runs a full sync
![image](https://github.com/microsoft/o365-moodle/assets/135825482/2d60fab5-bbf4-4f73-9b64-c91aa9ee75f0)

Recorded in the log
...... Error in delta usersync: Error in API call: Invalid request: Both skiptoken and deltatoken can't be in the same request.
...... Resetting delta tokens.

Regards,
Ray.

**Comment by RayCoSector** [comment]
Further: I installed 4.1.6 on our demo site today, up from 4.1.4 where it was not happening ... and it is not happening on their now. Was it possibly fixed in 4.1.6 plugin release ?

In hindsight I should have gone to 4.1.5 on here first !

**Comment by smangancap** [comment]
I can confirm this same issue persists in moodle version 4.1.9 and **local_o365 4.1.6**

**Comment by RayCoSector** [comment]
Any news or idea on what this might be @weilai-irl .. upgrading to **local_o365** 4.1.6 & **auth_oidc** 4.1.6 is still showing the same issues.

**Comment by RayCoSector** [comment]
Morning @weilai-irl sorry to be a pain, looking for a solution for this. I've had some success on some sites by using **Cleanup User Sync Delta Tokens** in Maintenance Tools section. But this does not fix it for all sites.

I've now seen this on a Moodle 4.4 site using plugins local_o365 / auth_oidc version 4.3.3

Many thanks for any help or pointers to solve the issue.

Regards,
Ray.

**Comment by bbusschots-mu** [comment]
We're having this problem too, this is what our Moodle Partner has found when investigating our issues:

> Upon reviewing the logs, I've identified a recurring error message indicating an issue with the API call during delta user synchronization. The error states: "Error in API call: Invalid request: Both skiptoken and deltatoken can't be in the same request."
> 
> This error seems to disrupt the synchronization process, leading to the inability to retrieve the delta token for subsequent runs. After which the sync task ends up processing all users, resulting in a significant increase in server memory usage and, eventually, halting the cron job without providing an explicit error message.

For now we are limping along, with user update happening slowly, and we're often relying on users to log in to get their accounts to update.

We are running:
* Moodle 4.1.10 (Build: 20240422)
* local_o365 4.1.6 (2022112830)
* auth_oidc 4.1.6 (2022112830)

**Comment by bbusschots-mu** [comment]
Thanks @weilai-irl — I've put in the request to have the PR for the 4_0_1 branch applied to our test Moodle instance. I'll report back when I have news.

**Comment by RayCoSector** [comment]
Morning @weilai-irl 

I can confirm that adding the changes [mentioned here](https://github.com/microsoft/o365-moodle/pull/2565/files) to local/o365/classes/rest/unified.php fixes the issue.

Each Entra sync run now returns as expected

`Execute scheduled task: Sync users from Microsoft Entra ID (local_o365\task\usersync)
... started 11:37:14. Current memory use 19.2 MB.
...... Starting sync
...... Using deltatoken.
...... Using delta sync.
...... Contacting Microsoft Entra ID...
...... Got response from Microsoft Entra ID
...... Storing deltatoken
...... 3 users received. Syncing...
**Details removed**
...... Sync process finished.
... used 14 dbqueries
... used 11.851914167404 seconds
Scheduled task complete: Sync users from Microsoft Entra ID (local_o365\task\usersync)`

**Comment by weilai-irl** [comment]
Hi all,

The fix to this issue has been included in release 4.1.7, 4.2.6 and 4.3.4 on 2nd of July 2024. I'm going to mark this issue as closed.

Regards,
Lai
